trigger: none

variables:
  ARCHIVED_LOGS: "$(Build.ArtifactStagingDirectory)/questdb-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS).zip"

stages:
  - stage: BuildAndTest
    displayName: "Building and testing"
    jobs:
      - job: RunOn
        displayName: "on"
        strategy:
          matrix:
            linux-x64:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
              jdkArch: "x64"
            mac-aarch64:
              imageName: "macos-15-arm64"
              poolName: "Azure Pipelines"
              jdkArch: "arm64"
            mac-x64:
              imageName: "macos-15"
              poolName: "Azure Pipelines"
              jdkArch: "x64"
            windows-msvc-2022-x64:
              imageName: "windows-2022"
              poolName: "Azure Pipelines"
              jdkArch: "x64"
        pool:
          name: $(poolName)
          vmImage: $(imageName)
        timeoutInMinutes: 60
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: false
          - template: setup.yaml
          - script: git clone --depth 1 https://github.com/questdb/questdb.git ./questdb
            displayName: git clone questdb
          - task: Maven@3
            displayName: "Compile QuestDB"
            inputs:
              mavenPOMFile: "questdb/pom.xml"
              jdkVersionOption: "default"
              options: "-DskipTests -Pbuild-web-console"
          - template: questdb_start.yaml
            parameters:
              configPath: "ci/default"
          - task: Maven@3
            displayName: "Run Client Tests"
            inputs:
              mavenPOMFile: "pom.xml"
              jdkVersionOption: "default"
              goals: "test"
          - task: ArchiveFiles@2
            displayName: "Tests failed -- Compress logs"
            condition: failed()
            inputs:
              rootFolderOrFile: "logs"
              includeRootFolder: false
              archiveFile: $(ARCHIVED_LOGS)
          - task: PublishBuildArtifacts@1
            displayName: "Tests failed -- Upload logs"
            condition: failed()
            inputs:
              pathToPublish: $(ARCHIVED_LOGS)
              artifactName: MavenFailedTestsLogs
          - script: |
              echo "Stopping QuestDB server..."
              pkill -f io.questdb.ServerMain || true
            displayName: "Stop QuestDB server"
            condition: not(startsWith(variables['imageName'], 'windows'))
          - powershell: |
              Write-Host "Stopping QuestDB server..."
              Get-Process -Name "java" -ErrorAction SilentlyContinue | Where-Object { $_.CommandLine -like "*io.questdb.ServerMain*" } | Stop-Process -Force -ErrorAction SilentlyContinue
            displayName: "Stop QuestDB server on Windows"
            condition: startsWith(variables['imageName'], 'windows')
