trigger: none

variables:
  ARCHIVED_LOGS: "$(Build.ArtifactStagingDirectory)/questdb-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS).zip"

stages:
  - stage: BuildAndTest
    displayName: "Building and testing"
    jobs:
      - job: RunOn
        displayName: "on"
        strategy:
          matrix:
            linux-x64:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
              jdkArch: "x64"
            mac-aarch64:
              imageName: "macos-15-arm64"
              poolName: "Azure Pipelines"
              jdkArch: "arm64"
            mac-x64:
              imageName: "macos-15"
              poolName: "Azure Pipelines"
              jdkArch: "x64"
            windows-msvc-2022-x64:
              imageName: "windows-2022"
              poolName: "Azure Pipelines"
              jdkArch: "x64"
        pool:
          name: $(poolName)
          vmImage: $(imageName)
        timeoutInMinutes: 60
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: false
          - template: setup.yaml
          - template: local_tests.yaml
