set(CMAKE_SYSTEM_NAME               Windows)
set(CMAKE_SYSTEM_PROCESSOR          x86_64)

set(QDB_WIN_TOOLCHAIN_PATH_ARGS)
if (WIN_TOOLCHAIN_PATH)
    list(APPEND QDB_WIN_TOOLCHAIN_PATH_ARGS PATHS "${WIN_TOOLCHAIN_PATH}" NO_DEFAULT_PATH)
endif ()

function(qdb_find_win_tool out)
    find_program(${out} NAMES ${ARGN} ${QDB_WIN_TOOLCHAIN_PATH_ARGS})
    if (NOT ${out})
        find_program(${out} NAMES ${ARGN})
    endif ()
    if (NOT ${out})
        list(GET ARGN 0 tool)
        set(${out} "${WIN_TOOLCHAIN_PATH}${tool}${CMAKE_EXECUTABLE_SUFFIX}" CACHE FILEPATH "Windows toolchain ${tool}" FORCE)
    endif ()
endfunction()

qdb_find_win_tool(QDB_WIN_AR x86_64-w64-mingw32-ar ar)
qdb_find_win_tool(QDB_WIN_ASM_COMPILER x86_64-w64-mingw32-gcc)
qdb_find_win_tool(QDB_WIN_C_COMPILER x86_64-w64-mingw32-gcc)
qdb_find_win_tool(QDB_WIN_CXX_COMPILER x86_64-w64-mingw32-g++)
qdb_find_win_tool(QDB_WIN_LINKER x86_64-w64-mingw32-ld ld)
qdb_find_win_tool(QDB_WIN_OBJCOPY x86_64-w64-mingw32-objcopy objcopy)
qdb_find_win_tool(QDB_WIN_RANLIB x86_64-w64-mingw32-ranlib ranlib)
qdb_find_win_tool(QDB_WIN_SIZE x86_64-w64-mingw32-size size)
qdb_find_win_tool(QDB_WIN_STRIP x86_64-w64-mingw32-strip strip)

set(CMAKE_AR                        ${QDB_WIN_AR})
set(CMAKE_ASM_COMPILER              ${QDB_WIN_ASM_COMPILER})
set(CMAKE_C_COMPILER                ${QDB_WIN_C_COMPILER})
set(CMAKE_CXX_COMPILER              ${QDB_WIN_CXX_COMPILER})
set(CMAKE_LINKER                    ${QDB_WIN_LINKER})
set(CMAKE_OBJCOPY                   ${QDB_WIN_OBJCOPY})
set(CMAKE_RANLIB                    ${QDB_WIN_RANLIB})
set(CMAKE_SIZE                      ${QDB_WIN_SIZE})
set(CMAKE_STRIP                     ${QDB_WIN_STRIP})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
